baseurl = "/"
languageCode = "en-us"
title = "I'm a Chordata! Urochordata!"
theme = "hamburg"
googleAnalytics = "UA-9734501-1"
disqusShortname = "im-a-chordata-urochordata"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeURLs = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"


# Pagination
paginate = 5
paginatePath = "page"

#theme specific
# general
[outputs]
home = ["HTML", "RSS"]

[permalinks]
    post = "/:year/:month/:day/:slug/"



[params]
    description = "Marine Data Science for All, Regardless of Backbone! Built through Hugo and blogdown."


    friends = false
    bookmarks = false
    about_me = true

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    
    disqus = "im-a-chordata-urochordata"
    ga_api_key = "UA-9734501-1"


#theme specific

	subtitle = "Marine Data Science for All, Regardless of Backbone!"
    # Short subtitle/tagline. This is displayed in the header.
    themecolor = "#FFFFFF" # Defines the tab color in Chrome for Android.
    # To load additional CSS styles
    customCSS = ['hamburg.css']
    
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Categories"
    url = "/categories/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/jebyrnes"
[[menu.main]]    
    name = "Lab Site"
    url = "https://byrneslab.net"


[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


[params.social]
    rss            = true
    #email          = "jarrett.byrnes@gmail.com"
    #twitter       = "http://twitter.com/jebyrnes"
    github         = "https://github.com/jebyrnes"
    bluesky        = "https://bsky.app/profile/jebyrnes.bsky.social"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
